theme: minima

title: Abinav Karthikeyan R
email: abhinavkarthikeyan1999@gmail.com
url: "https://abinav-karthikeyan.github.io"
baseurl: "/abinav_karthikeyan_r.github.io"

permalink: /blog/:year/:month/:day/:title/

minima:
  skin: auto

header_pages:
  - about.md
  - interests.md
  - blog.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
